version: 0.2

phases:
  pre_build:
    commands:
      - node --version
      - npm --version
      - npm install -g pnpm
  build:
    commands:
      - echo Build started on `date`
      - pnpm install
      - pnpm run test
      - pnpm run generate
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id E27NMC5UIA7ZLG --paths '/*'
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: '.output/public'